### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by Fivesix567** [S3cur3Th1sSh1t/SharpImpersonation#1]
[*] Changing WINSTA/Desktop permissions for the target user: NT AUTHORITY\SYSTEM
 [*] Setting Permission for : NT AUTHORITY\SYSTEM

[*] Stealing token from ProcID: 2256 to start binary: powershell.exe whoami
[+] Recieved Handle for:  (2256)
 [+] Process Handle: 0x02D4
[+] Primary Token Handle: 0x02D8
 [+] Duplicate Token Handle: 0x02D4
[*] Adjusting Token Privilege
SeAuditPrivilege
 [+] Recieved luid
 [*] AdjustTokenPrivilege
 [+] Adjusted Privilege: SeAuditPrivilege
 [+] Privilege State: SE_PRIVILEGE_ENABLED
[*] CreateProcessWithTokenW
Starting C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe with arguments whoami
Directory: C:\Users\Administrator\Desktop
Tried starting process, return value is False
 [-] Function CreateProcessWithTokenW failed:
[-] Access denied.

**Comment by S3cur3Th1sSh1t** [comment]
This is strange. From all the output above this should have worked. Can you use another technique than `CreateProcessWithTokenW`?

**Comment by S3cur3Th1sSh1t** [comment]
As no response came I’m gonna close this. Feel free to reopen if you still face the issue.
