### ISSUE TITLE
The directory name is invalid (PSEXEC)

### ISSUE THREAD

**Issue by anonymouxios** [S3cur3Th1sSh1t/SharpImpersonation#3]
Hi, when i run program with psexec, i got this error, how can i solve the problem ?

[*] CreateProcessWithLogonW
 [-] Function CreateProcessWithLogonW failed:
 [-] The directory name is invalid

**Comment by S3cur3Th1sSh1t** [comment]
See https://github.com/S3cur3Th1sSh1t/SharpImpersonation/issues/2
